language: python
dist: trusty
sudo: false
cache: pip
python: 3.6

os:
  - linux
dist:
  - xenial
compiler:
  - gcc

# install dependencies
addons:
  apt:
    update: true
    packages:
      - libhdf5-serial-dev
      - zlib1g-dev
      - libatlas-base-dev
      - lcov
      - swig3.0
      - libpcsclite-dev

install:
  - mkdir -p ~/bin/ && ln -s /usr/bin/swig3.0 ~/bin/swig && export PATH=~/bin/:$PATH
  - pip install -e .[ci] # Install with CI deps
  - pip install -e .[yubikey]

script:
  - pre-commit run --all-files
  - pytest taf/tests
  # - pytest --cov-report term-missing --cov=taf taf/tests/ --cov-fail-under 95
