on:
  push:
    branches:
      - main
      - test-github-actions
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        os: [ubuntu-latest, windows-2019]
        python-version: ["3.7", "3.8", "3.9", "3.10"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        if: matrix.os == 'ubuntu-latest'
        run: |
          sudo apt-get update
          sudo apt-get install -y libhdf5-serial-dev zlib1g-dev libatlas-base-dev lcov swig3.0 libpcsclite-dev
          mkdir -p ~/bin/ && ln -s /usr/bin/swig3.0 ~/bin/swig && export PATH=~/bin/:$PATH
          pip install -e .[ci,test,yubikey]

      - name: setup github user
        shell: bash
        run: |
          git config --global user.name oll-bot
          git config --global user.email developers@openlawlib.org

      - name: Run pre-commit and test with pytest
        run: |
          pre-commit run --all-files
          pytest taf/tests

      - name: Build standalone executable with Docker (Linux)
        if: matrix.os == 'ubuntu-latest'
        run: |
          docker build -t taf-linux -f .github/dockerimages/Dockerfile.linux .
          docker cp $(docker create --rm taf-linux):/usr/src/app/taf/dist/taf taf-linux

      - name: Build standalone executable with Docker (Windows)
        if: matrix.os == 'windows-2019'
        run: |
          docker build -t taf-windows -f .github/dockerimages/Dockerfile.windows .
          docker cp $(docker create --rm taf-windows):/taf/dist/taf.exe taf-windows

      - name: Test standalone executable (Linux)
        if: matrix.os == 'ubuntu-latest'
        id: test-linux
        run: |
          ./taf-linux --help > actual_output.txt
          if ! diff -q actual_output.txt expected_output.txt; then
            echo "Output does not match expected result"
            echo "upload=false" >> $GITHUB_ENV
            exit 1
          else
            echo "upload=true" >> $GITHUB_ENV
          fi

      - name: Test standalone executable (Windows)
        if: matrix.os == 'windows-2019'
        id: test-windows
        run: |
          taf-windows.exe --help > actual_output.txt
          if ! diff -q actual_output.txt expected_output.txt; then
            echo "Output does not match expected result"
            echo "upload=false" >> $GITHUB_ENV
            exit 1
          else
            echo "upload=true" >> $GITHUB_ENV
          fi

      - name: Upload standalone executable (Linux)
        if: matrix.os == 'ubuntu-latest' && env.upload == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: taf-executable-linux
          path: taf-linux

      - name: Upload standalone executable (Windows)
        if: matrix.os == 'windows-2019' && env.upload == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: taf-executable-windows
          path: taf-windows
