on:
  push: {}
  pull_request:
    types: [closed]
  release:
    types: [published]

jobs:
  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libhdf5-serial-dev zlib1g-dev libatlas-base-dev lcov swig3.0 libpcsclite-dev
          mkdir -p ~/bin/ && ln -s /usr/bin/swig3.0 ~/bin/swig && export PATH=~/bin/:$PATH
          pip install -e .[ci,test,yubikey]

      - name: setup github user
        run: |
          git config --global user.name oll-bot
          git config --global user.email developers@openlawlib.org

      - name: Run pre-commit and test with pytest
        run: |
          pre-commit run --all-files
          pytest taf/tests

  build-and-test-executables:
    needs: run-tests
    runs-on: ubuntu-latest
    if: ${{ needs.run-tests.result == 'success' }}
    steps:
      - uses: actions/checkout@v3

      - name: Build standalone executable with Docker (Linux)
        run: |
          docker build -t taf-linux -f .github/dockerimages/Dockerfile.linux .
          docker cp $(docker create --rm taf-linux):/usr/src/app/taf/dist/taf taf-linux

      - name: Build standalone executable with Docker (Windows)
        run: |
          docker build -t taf-windows -f .github/dockerimages/Dockerfile.windows .
          docker cp $(docker create --rm taf-windows):/taf/dist/taf.exe taf-windows

      - name: Build standalone executable with Docker (macOS)
        run: |
          docker build -t taf-macos -f .github/dockerimages/Dockerfile.macos .
          docker cp $(docker create --rm taf-macos):/usr/src/app/taf/dist/taf taf-macos

      - name: Test standalone executable (Linux)
        id: test-linux
        run: |
          ./taf-linux --help > actual_output.txt
          echo "Expected Output:"
          echo "Usage: taf [OPTIONS] COMMAND [ARGS]..." > expected_output.txt
          echo "" >> expected_output.txt
          echo "  TAF Command Line Interface" >> expected_output.txt
          cat expected_output.txt
          echo "Actual Output:"
          cat actual_output.txt
          if ! grep -q -F "$(cat expected_output.txt)" actual_output.txt; then
            echo "Output does not match expected result"
            echo "upload-linux=false" >> $GITHUB_ENV
            exit 1
          else
            echo "upload-linux=true" >> $GITHUB_ENV
          fi
      
      - name: Test standalone executable (Windows)
        id: test-windows
        run: |
          taf-windows.exe --help > actual_output.txt
          echo "Expected Output:"
          echo "Usage: taf [OPTIONS] COMMAND [ARGS]..." > expected_output.txt
          echo "" >> expected_output.txt
          echo "  TAF Command Line Interface" >> expected_output.txt
          cat expected_output.txt
          echo "Actual Output:"
          cat actual_output.txt
          if ! grep -q -F "$(cat expected_output.txt)" actual_output.txt; then
            echo "Output does not match expected result"
            echo "upload-windows=false" >> $GITHUB_ENV
            exit 1
          else
            echo "upload-windows=true" >> $GITHUB_ENV
          fi
      
      - name: Test standalone executable (macOS)
        id: test-macos
        run: |
          ./taf-macos --help > actual_output.txt
          echo "Expected Output:"
          echo "Usage: taf [OPTIONS] COMMAND [ARGS]..." > expected_output.txt
          echo "" >> expected_output.txt
          echo "  TAF Command Line Interface" >> expected_output.txt
          cat expected_output.txt
          echo "Actual Output:"
          cat actual_output.txt
          if ! grep -q -F "$(cat expected_output.txt)" actual_output.txt; then
            echo "Output does not match expected result"
            echo "upload-macos=false" >> $GITHUB_ENV
            exit 1
          else
            echo "upload-macos=true" >> $GITHUB_ENV
          fi


      - name: Upload standalone executable (Linux)
        if: env.upload-linux == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: taf-executable-linux
          path: taf-linux

      - name: Upload standalone executable (Windows)
        if: env.upload-windows == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: taf-executable-windows
          path: taf-windows

      - name: Upload standalone executable (macOS)
        if: env.upload-macos == 'true'
        uses: actions/upload-artifact@v3
        with:
          name: taf-executable-macos
          path: taf-macos
