name: Pytest Benchmark Test
on:
  push:
    branches:
      - PytestBenchmarkTesting
permissions:
  contents: write
  deployments: write

jobs:
  benchmark:
    name: Run benchmarking
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: 3.10.16
      - name: Run benchmark
        run: |
          pip install -r requirements.txt
          pytest -k "test_benchmark_clone_valid_happy_path" --benchmark-json output.json

      - name: Store benchmark result
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: Python Benchmark with pytest-benchmark
          tool: 'pytest'
          output-file-path: examples/pytest/output.json
          # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t/github-action-not-triggering-gh-pages-upon-push/16096
          github-token: ${{ secrets.GITHUB_TOKEN }}
          auto-push: true
          # Show alert with commit comment on detecting possible performance regression
          alert-threshold: '120%'
          comment-on-alert: true
          fail-on-alert: true
          alert-comment-cc-users: '@ktrz'

      # - name: Store benchmark result - separate results repo
      #   uses: benchmark-action/github-action-benchmark@v1
      #   with:
      #     name: Python Benchmark with pytest-benchmark
      #     tool: 'pytest'
      #     output-file-path: examples/pytest/output.json
      #     # Use personal access token instead of GITHUB_TOKEN due to https://github.community/t/github-action-not-triggering-gh-pages-upon-push/16096
      #     github-token: ${{ secrets.BENCHMARK_ACTION_BOT_TOKEN }}
      #     auto-push: true
      #     # Show alert with commit comment on detecting possible performance regression
      #     alert-threshold: '200%'
      #     comment-on-alert: true
      #     fail-on-alert: true
      #     alert-comment-cc-users: '@ktrz'
      #     gh-repository: 'github.com/benchmark-action/github-action-benchmark-results'
